e=Edit(12,'SpriteRenderer가 Mesh·Material·Texture·Transform을 연결하는 역할을 읽습니다. 아래 본문에는 일반적인 스프라이트 시스템의 확장 설계도 포함되어 있습니다.','실제 저장소의 기본 Draw 경로와 Tint·Flip·Atlas·Batching 확장 설계를 구분합니다.','flowchart LR\n    C[카메라 View·Projection] --> B[BaseRenderer: Transform·Material·Mesh]\n    B --> T[Sprite Texture 바인딩]\n    T --> D[BaseRenderer Draw]')
e.guide+='\n### 저장소 코드와 이 문서의 범위\n\n**현재 구현은 `BaseRenderer`를 상속합니다.** 뒤의 Component 직접 상속·Tint·Flip·Sorting Layer·9-slice·Batcher 예제는 확장 학습 모델입니다. 해당 함수 이름만으로 현재 엔진에 그 기능이 구현되었다고 판단하지 않습니다.\n\n```c++\nvoid SpriteRenderer::Render(const Matrix& view, const Matrix& projection)\n{\n    BaseRenderer::Render(view, projection);\n    Texture* texture = mSprite ? mSprite : Resources::Find<Texture>(L"DefaultWhiteTexture");\n    if (texture) texture->Bind(eShaderStage::PS, UINT(eTextureType::Sprite));\n    BaseRenderer::Draw();\n}\n```\n\n출처: [ce56f16 · 실제 SpriteRenderer.cpp](https://github.com/eazuooz/YamYam_Engine/blob/ce56f16dd7a40fd2b4bf03c680790e5b637c7530/YamYamEngine_CORE/yaSpriteRenderer.cpp). DX11 시점의 [8b4ed4a](https://github.com/eazuooz/YamYam_Engine/blob/8b4ed4a/YamYamEngine_SOURCE/yaSpriteRenderer.cpp)에도 카메라 행렬을 Render 인자로 받는 구조가 있습니다. MainCamera 전역값으로 고정하면 다중 카메라 출력이 틀어질 수 있습니다.\n'
e.para('- 스프라이트 애니메이션, 플리핑, 색상','- 스프라이트 애니메이션, 플리핑, 색상 조정은 추가할 수 있는 기능이며 아래에서 확장 방법을 살펴봅니다.')
e.para('- 자동 배치(Batching)로 드로우 콜 감소','- 자동 배치는 별도 Batch 수집·GPU 제출 경로를 구현했을 때 드로우 콜을 줄입니다.')
e.block_replace(0,'        graphics::Texture* mSprite;', '        Mesh* CreateQuadMesh(); // 아래 확장 예제의 함수 선언\n        graphics::Texture* mSprite;')
e.block_replace(1,'        Resources::Insert(L"RectMesh", mMesh);','        if (mMesh) Resources::Insert(L"RectMesh", mMesh);')
e.block_replace(2,'    Mesh* mesh = new Mesh();','    for (auto& v : vertices) v.color = Vector4(1.f, 1.f, 1.f, 1.f);\n    Mesh* mesh = new Mesh();')
e.block_replace(2,'    mesh->CreateVertexBuffer(vertices.data(), vertices.size());\n    mesh->CreateIndexBuffer(indices.data(), indices.size());','    if (!mesh->CreateVB(vertices) || !mesh->CreateIB(indices))\n    { delete mesh; return nullptr; }')
old=e.blocks[4][3]; start=old.index('        Vector3 scale'); end=old.index('\n    }',start)
e.block_replace(4,old[start:end],'        // 기존 world(부모 변환 포함) 앞에 로컬 반전을 적용합니다.\n        world = Matrix::CreateScale(mFlipX ? -1.f : 1.f,\n            mFlipY ? -1.f : 1.f, 1.f) * world;')
e.block_replace(4,'TransformCB transformData;','TransformCB transformData = {};')
e.block_replace(4,'ColorCB colorData;','ColorCB colorData = {};')
e.block_replace(4,'mSprite->BindShader(eShaderStage::PS, 0);','mSprite->Bind(eShaderStage::PS, 0);')
e.block_replace(4,'    mSprite->Clear();','    Texture::Clear(eShaderStage::PS, 0);')
e.block_replace(5,'    matrix ', '    row_major matrix ')
for a,b in [('SpriteRenderer* mRenderer;','SpriteRenderer* mRenderer = nullptr;'),('int mCurrentFrame;','size_t mCurrentFrame = 0;'),('float mFrameTime;','float mFrameTime = 0.1f;'),('float mElapsedTime;','float mElapsedTime = 0.f;')]:e.block_replace(10,a,b)
e.block_replace(10,'        mElapsedTime += Time::DeltaTime();','        if (!mRenderer || mFrames.empty() || mFrameTime <= 0.f) return;\n        mElapsedTime += Time::DeltaTime();')
e.block_replace(10,'        if (mElapsedTime >= mFrameTime)','        while (mElapsedTime >= mFrameTime)')
e.block_replace(10,'mElapsedTime = 0.0f;','mElapsedTime -= mFrameTime;')
e.block_replace(14,'// 모든 스프라이트를 하나의 드로우 콜로 렌더링','// 호환되는 Texture/Material/State별로 모으고 투명 정렬 순서 유지\n        // 각 배치를 인스턴스 버퍼와 맞는 Input Layout으로 제출')
e.block_replace(15,'return mSpriteRects[name];','return mSpriteRects.at(name); // 없는 이름이면 오류 처리, 새 항목을 삽입하지 않음')
e.block_replace(15,'// Vertex Shader에서 UV 오프셋 적용\noutput.UV = input.UV * UVScale + UVOffset;','// HLSL VS에서 적용할 식: output.UV = input.UV * UVScale + UVOffset;')
e.finish('### 확장 예제 연결 시 확인\n\nTint 예제는 HLSL b1과 같은 레이아웃의 C++ ColorCB, 생성된 상수 버퍼, 올바른 바인딩이 필요합니다. 예시의 World/View/Projection은 `row_major`로 선언했으므로 C++ 행렬을 그대로 전달하는 규약입니다. 최신 엔진의 기본 column-major HLSL과 CPU 전치 규약과 섞지 않습니다. 음수 스케일 반전은 winding도 뒤집으므로 culling 설정을 확인합니다.\n\nSortingOrder 필드만 추가해도 자동 정렬되지는 않습니다. 카메라가 Draw 목록을 수집할 때 이 키를 실제로 비교해야 합니다. 현재 DX12는 Opaque/CutOut/Transparent별 카메라 거리 정렬을 사용합니다. Atlas의 Rect 맵 역시 이미지 패킹 알고리즘 자체가 아닙니다. 풀은 GameObject 소유자와 중복 등록·반환 규칙을 정해야 하며, 렌더러별 통계는 실제 Draw가 일어난 시점에 더합니다.\n<mention-page url="'+NEW2+'"/>')

e=Edit(13,'Rasterizer·Depth/Stencil·Blend가 각각 도형 처리, 가시성 판정, 색 합성을 맡는다는 점부터 읽습니다.','불투명·CutOut·반투명에서 Draw 순서와 깊이 쓰기·블렌드 설정을 함께 설명할 수 있습니다.')
e.para('이 세 가지 State는 Output Merger','DirectX 11에서 Rasterizer State는 래스터라이저 단계에, Depth/Stencil과 Blend State는 출력 병합 동작에 관여합니다. 깊이 검사는 조건에 따라 픽셀 셰이더보다 일찍 수행될 수도 있습니다.')
e.para('- 성능 최적화: 약 50%','- 닫힌 메시의 보이지 않는 뒷면 작업을 줄일 수 있습니다. 전체 GPU 부하가 항상 50% 줄어드는 것은 아닙니다.')
e.para('- NDC 좌표(-1','- Direct3D NDC의 x·y는 [-1, 1], z는 [0, 1]입니다. viewport는 이를 화면 좌표와 MinDepth~MaxDepth로 매핑합니다.')
e.para('- MRT 사용 시 TRUE로','- MRT에서 서로 다른 블렌드 설정이 필요할 때 TRUE로 설정합니다. MRT 자체의 필수 조건은 아닙니다.')
e.para('- 알파 값은 무시됨','- 알파는 블렌드 계수로 쓰이지 않지만 쓰기 마스크가 허용하면 RT의 알파 채널에 저장됩니다.')
e.para('- 각 픽셀의 깊이(카메라로부터의 거리)','- 각 샘플의 투영된 깊이를 저장합니다. 일반적인 원근 투영에서는 카메라와의 선형 거리와 다릅니다.')
e.para('3. **Pixel Shader**: 테스트 통과','3. **Pixel Shader와의 관계**: 위 목록은 개념적 조건입니다. early depth/stencil 가능 여부는 셰이더의 discard·깊이 출력 등과 GPU 경로에 따라 달라집니다.')
e.para('- **LESS_EQUAL**: LESS + 같은','- **LESS_EQUAL**: 같은 깊이도 통과시킵니다. Z-fighting의 정밀도 문제를 자동으로 해결하지 않습니다.')
e.para('- State 변경은 GPU 파이프라인 플러시','- State 변경은 드라이버·GPU 작업 비용을 늘릴 수 있지만 모든 변경이 전체 파이프라인 flush를 유발하는 것은 아닙니다.')
e.para('2. 스카이박스 (깊이 테스트 비활성화)','2. 스카이박스: 마지막에 그린다면 일반적으로 far 깊이에서 LessEqual 검사·깊이 쓰기 끔을 사용합니다. 깊이를 끄고 불투명 물체 뒤에 그리면 기존 화면을 덮을 수 있습니다.')
e.block_replace(1,'// MSAA 비활성화','// 래스터라이저의 멀티샘플 동작 설정, RT의 SampleDesc와 별개')
e.block_replace(11,'// false면 RT[0]만 사용, RT[1-7] 무시','// false면 RT[0] 설정을 모든 RT에 적용')
e.block_replace(16,'// 바인딩 시 팩터 값 지정','// 변경된 desc로 새 BlendState를 생성한 뒤 바인딩합니다.\n// 기존 객체는 desc 메모리를 바꿔도 자동 변경되지 않습니다.\n// 바인딩 시 팩터 값 지정')
e.block_replace(17,'NonPremultiplied','Premultiplied')
e.block_replace(17,'비사전곱셈 알파','사전곱셈 알파')
e.block_replace(17,'    // 3. Additive: 가산 블렌딩 (파티클 효과)','    // 3. Additive: 알파 가중 가산 SRC.rgb * SRC.a + DEST.rgb')
e.block_replace(17,'    device->CreateBlendState(&desc, &states[Premultiplied]);','    desc.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;\n    device->CreateBlendState(&desc, &states[Premultiplied]);')
e.block_replace(6,'D3D11_RASTERIZER_DESC desc = {};','D3D11_RASTERIZER_DESC desc = CD3D11_RASTERIZER_DESC(D3D11_DEFAULT);')
e.block_replace(17,'D3D11_BLEND_DESC desc = {};','D3D11_BLEND_DESC desc = CD3D11_BLEND_DESC(D3D11_DEFAULT);')
e.block_replace(24,'D3D11_DEPTH_STENCIL_DESC desc = {};','D3D11_DEPTH_STENCIL_DESC desc = CD3D11_DEPTH_STENCIL_DESC(D3D11_DEFAULT);')
e.block_replace(24,'    // 5. StencilRead: 스텐실 마스크 영역만 렌더링','    // 5. StencilRead: 스텐실 마스크 영역만 렌더링\n    desc.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;\n    desc.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;\n    desc.StencilReadMask = 0xFF;\n    desc.StencilWriteMask = 0;')
e.block_replace(24,'    device->CreateDepthStencilState(&desc, &states[StencilRead]);','    desc.BackFace = desc.FrontFace;\n    device->CreateDepthStencilState(&desc, &states[StencilRead]);')
for n,en,func in [(6,'eRasterizerState','CreateRasterizerState'),(17,'eBlendState','CreateBlendState'),(24,'eDepthStencilState','CreateDepthStencilState')]:
    code=e.code_changes[n][0]
    code=re.sub(r'device->'+func+r'\(&desc, &states\[(\w+)\]\);',lambda m:'if (FAILED(device->'+func+'(&desc, states[static_cast<size_t>('+en+'::'+m[1]+')].GetAddressOf())))\n        throw std::runtime_error("State creation failed");',code)
    e.block(n,code,caption='초기화 예시 — device·해당 열거형 크기의 ComPtr 배열 states·stdexcept 필요')
e.block(27,'스텐실 아웃라인 패스 설계\n1. 프레임 시작 때 stencil=0으로 clear\n2. 본체 Draw: 깊이 검사 통과 시 stencil을 1로 기록\n3. 외곽 Draw: 확대 또는 법선 방향으로 확장한 메시를 stencil!=1 영역에 그림\n4. 외곽용 단색 Shader와 필요한 깊이 정책을 실제 Draw에 사용\n5. 원래 Transform·Material·상태 복원\n일반 obj->Render가 내부에서 Material을 다시 바인딩하면 외곽 Shader가 덮입니다.\n별도 Draw 패스 또는 Material override 경로가 필요합니다.','plain text',caption='확장 패스 설계 — StencilRef와 Material 재바인딩까지 연결해야 완성')
e.block(31,'Depth pre-pass 설계\n1. 색상 쓰기 마스크 0 + 깊이 검사/쓰기 켬으로 불투명 기하 렌더링\n2. 동일한 정점 변환 + 깊이 Equal(또는 정책에 따른 LessEqual), 쓰기 끔\n3. 색상 쓰기 켬으로 조명 패스 렌더링\n4. 다음 패스의 상태 복원\n두 번째 패스를 LESS로 설정하면 첫 패스가 쓴 같은 깊이가 실패합니다.\nCutOut은 두 패스의 clip 조건도 같아야 하며, 이중 기하 처리 비용을 측정합니다.','plain text')
e.finish('### 상태 예제와 YamYam의 실제 정책\n\nenum 블록은 SDK 상수의 의미를 설명하는 목록입니다. 일부 값과 항목을 생략했으므로 헤더의 enum을 다시 선언하지 않습니다. 상태 객체는 생성 후 불변이며 desc 변경 후에는 새 객체를 생성해야 합니다. 초기화 예시의 생성 실패는 Release에서도 처리합니다.\n\n반투명 RGB 공식과 RT 알파 공식은 별개입니다. 이 문서의 AlphaBlend는 RGB에 SrcAlpha/InvSrcAlpha, 알파에 ONE/ZERO를 사용해 **출력 알파가 source 알파**가 됩니다. SrcOver 알파 누적이나 premultiplied 입력과 구분합니다.\n\n일반 3D 예제의 반투명은 깊이 검사를 유지하고 쓰기만 끕니다. 현재 YamYam DX12 복구 정책은 기존 DX11 동작을 따라 **Transparent = DepthFunc Always + 쓰기 끔**입니다. 뒤의 불투명 물체를 통과해서 겹쳐질 수 있으며, 일반 3D 표준 설정으로 소개하지 않습니다. 불투명 → CutOut → Transparent 순서, 카메라별 정렬, ImGui에서 RT 알파를 다시 곱하지 않도록 하는 처리는 다음 문서에서 실제 코드로 확인합니다.\n<mention-page url="'+NEW2+'"/>\n\n상태별 배치는 반투명 뒤→앞 순서를 깨뜨리지 않는 범위에서만 적용합니다. 교차하는 투명 메시·큰 메시의 정확한 픽셀 순서는 오브젝트 중심 거리 정렬만으로 해결되지 않습니다.')
